from django.conf.urls import patterns, url
from movies import constants

urlpatterns = patterns(
    '',
    url(r'^list/(?P<username>[\w.@+-]+)/watched/$',
        'movies.views.show_list',
        {'status': constants.WATCHED},
        name='list_watched'),
    url(r'^list/(?P<username>[\w.@+-]+)/plantowatch/$',
        'movies.views.show_list',
        {'status': constants.PLAN_TO_WATCH},
        name='list_plantowatch'),
    url(r'^list/(?P<username>[\w.@+-]+)/ignored/$',
        'movies.views.show_list',
        {'status': constants.IGNORED},
        name='list_ignored'),
    url(r'^list/(?P<username>[\w.@+-]+)/achievements/$',
        'movies.views.list_user_achievements',
        name='list_user_achievements'),
    url(r'^movie/(?P<movie_id>[\d]+)/(?P<slug>[\w-]*)/$',
        'movies.views.show_movie',
        name='movie'),
    url(r'^person/(?P<person_id>[\d]+)/(?P<slug>[\w-]+)/$',
        'movies.views.show_person',
        name='person'),
    url(r'^followers/(?P<username>[\w.@+-]+)/$',
        'movies.views.show_followers',
        name='followers'),
    url(r'^list/compare/(?P<first_username>[\w.@+-]+)/(?P<second_username>[\w.@+-]+)/shared/$',
        'movies.views.compare_list',
        {'mode': constants.COMPARE_MODE_SHARED},
        name='list_comparison'),
    url(r'^list/compare/(?P<first_username>[\w.@+-]+)/(?P<second_username>[\w.@+-]+)/unique/left/$',
        'movies.views.compare_list',
        {'mode': constants.COMPARE_MODE_UNIQUE_LEFT},
        name='list_comparison_unique_left'),
    url(r'^list/compare/(?P<first_username>[\w.@+-]+)/(?P<second_username>[\w.@+-]+)/unique/right/$',
        'movies.views.compare_list',
        {'mode': constants.COMPARE_MODE_UNIQUE_RIGHT},
        name='list_comparison_unique_right'),
    url(r'^list/compare/(?P<first_username>[\w.@+-]+)/(?P<second_username>[\w.@+-]+)/score-distribution/$',
        'movies.views.compare_list',
        {'mode': constants.COMPARE_MODE_SCORE_DISTRIBUTION},
        name='list_comparison_score_distribution'),
    url(r'^search/',
        'movies.views.search',
        name='search',
    ),
)
